/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/auth/get-session": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Current Session
     * @description Returns the active session when a valid session cookie is present.
     */
    get: operations["getSession"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/sign-in/email": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Sign In with Email
     * @description Authenticates a user using email and password credentials.
     */
    post: operations["signInWithEmail"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/sign-out": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Sign Out
     * @description Terminates the current session and clears the associated cookies.
     */
    post: operations["signOut"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/players": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Players */
    get: operations["listPlayers"];
    put?: never;
    /** Create Player */
    post: operations["createPlayer"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/players/{playerId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Player Details */
    get: operations["getPlayer"];
    /** Update Player */
    put: operations["updatePlayer"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/rounds": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Rounds */
    get: operations["listRounds"];
    put?: never;
    /** Record a Round */
    post: operations["createRound"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/rounds/latest": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Most Recent Round
     * @description Returns the most recently created round when available.
     */
    get: operations["getLatestRound"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/rounds/{roundId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Round Details */
    get: operations["getRound"];
    /** Edit a Round (within 24h) */
    put: operations["updateRound"];
    post?: never;
    /** Soft Delete a Round (within 24h) */
    delete: operations["deleteRound"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/fettmattis": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List FettMattis Entries */
    get: operations["listFettmattis"];
    put?: never;
    /** Create FettMattis */
    post: operations["createFettmattis"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/fettmattis/{fettmattisId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete FettMattis (within 24h) */
    delete: operations["deleteFettmattis"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/leaderboard/regular": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Regular Leaderboard */
    get: operations["getRegularLeaderboard"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/leaderboard/fettmattis": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Fettmattis Leaderboard */
    get: operations["getFettmattisLeaderboard"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/leaderboard/seasons": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Available Leaderboard Seasons */
    get: operations["listLeaderboardSeasons"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AuthUser: {
      /**
       * Format: uuid
       * @description UUID v7, time-ordered identifier for the authenticated user.
       */
      id: string;
      /** Format: email */
      email: string;
      name?: string | null;
      /** Format: uri */
      image?: string | null;
      /** @description Indicates whether the email address has been verified. */
      emailVerified?: boolean;
      /**
       * Format: date-time
       * @description Timestamp for when the user record was created.
       */
      createdAt?: string;
      /**
       * Format: date-time
       * @description Timestamp for the last update to the user record.
       */
      updatedAt?: string;
    };
    AuthSessionData: {
      /** @description Opaque bearer token for authenticated write operations. */
      token: string;
      /**
       * Format: date-time
       * @description Expiration timestamp for the session.
       */
      expiresAt?: string;
      /** @description Identifier for the issued session. */
      id?: string;
      /**
       * Format: date-time
       * @description Timestamp for when the session was created.
       */
      createdAt?: string;
      /**
       * Format: date-time
       * @description Timestamp for the last update to the session.
       */
      updatedAt?: string;
    };
    AuthSession: {
      session: components["schemas"]["AuthSessionData"];
      user: components["schemas"]["AuthUser"];
    };
    EmailPasswordSignInRequest: {
      /**
       * Format: email
       * @description Email address used for the account.
       */
      email: string;
      /**
       * Format: password
       * @description Password associated with the email account.
       */
      password: string;
      /**
       * Format: uri
       * @description Optional URL to redirect to after sign-in completes.
       */
      callbackURL?: string;
      /** @description When false, the session expires when the browser is closed. */
      rememberMe?: boolean;
    };
    EmailPasswordSignInResponse: {
      /** @description Indicates whether the client should perform a redirect. */
      redirect: boolean;
      /** @description Session token that can be exchanged for authenticated requests. */
      token: string;
      /**
       * Format: uri
       * @description Redirect destination when `redirect` is true.
       */
      url?: string | null;
      user: components["schemas"]["AuthUser"];
    };
    SignOutResponse: {
      /** @description Indicates that the user session was terminated. */
      success: boolean;
    };
    Player: {
      /**
       * Format: uuid
       * @description UUID v7, time-ordered identifier.
       */
      id: string;
      display_name: string;
      active: boolean;
    };
    PlayerCreate: {
      display_name: string;
    };
    PlayerUpdate: {
      display_name?: string;
      active?: boolean;
    };
    Round: {
      /**
       * Format: uuid
       * @description UUID v7, time-ordered identifier.
       */
      id: string;
      /** Format: date-time */
      created_at: string;
      participants: components["schemas"]["Player"][];
      loser: components["schemas"]["Player"];
    };
    RoundCreate: {
      participant_ids: string[];
      /**
       * Format: uuid
       * @description UUID v7, time-ordered identifier.
       */
      loser_id: string;
    };
    RoundUpdate: {
      participant_ids?: string[];
      /**
       * Format: uuid
       * @description UUID v7, time-ordered identifier.
       */
      loser_id?: string;
    };
    FettMattis: {
      /**
       * Format: uuid
       * @description UUID v7, time-ordered identifier.
       */
      id: string;
      player: components["schemas"]["Player"];
      /**
       * Format: uuid
       * @description UUID v7, time-ordered identifier.
       */
      round_id?: string | null;
      /** Format: date-time */
      created_at: string;
    };
    FettMattisCreate: {
      /**
       * Format: uuid
       * @description UUID v7, time-ordered identifier.
       */
      player_id: string;
      /**
       * Format: uuid
       * @description UUID v7, time-ordered identifier.
       */
      round_id?: string | null;
    };
    RegularLeaderboardItem: {
      player: components["schemas"]["Player"];
      rank: number;
      /** Format: float */
      loss_percentage: number;
      participation_count: number;
      loss_count: number;
    };
    FettmattisLeaderboardItem: {
      player: components["schemas"]["Player"];
      rank: number;
      fettmattis_count: number;
    };
    LeaderboardSeasonsResponse: {
      /** @description Years with leaderboard data available. */
      seasons: number[];
    };
    /** @description RFC 9457 Problem Details */
    Problem: {
      /**
       * Format: uri
       * @default about:blank
       */
      type: string;
      title: string;
      status: number;
      detail?: string;
      /** Format: uri */
      instance?: string;
    };
  };
  responses: {
    /** @description The request body is invalid. */
    BadRequest: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
    /** @description Authentication is required for this operation. */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
    /** @description The requested resource was not found. */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
    /** @description The action is forbidden, e.g., editing an item outside the 24h window. */
    Forbidden: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
    /** @description The resource already exists or the request conflicts with the current state. */
    Conflict: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getSession: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The current session details or null when no session is available. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthSession"] | null;
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  signInWithEmail: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EmailPasswordSignInRequest"];
      };
    };
    responses: {
      /** @description Session token and user details for the authenticated user. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmailPasswordSignInResponse"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
    };
  };
  signOut: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Confirmation that the session was terminated. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SignOutResponse"];
        };
      };
      400: components["responses"]["BadRequest"];
    };
  };
  listPlayers: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A list of players. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Player"][];
        };
      };
    };
  };
  createPlayer: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PlayerCreate"];
      };
    };
    responses: {
      /** @description Player created successfully. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Player"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      409: components["responses"]["Conflict"];
    };
  };
  getPlayer: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        playerId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Player details. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Player"];
        };
      };
      404: components["responses"]["NotFound"];
    };
  };
  updatePlayer: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        playerId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PlayerUpdate"];
      };
    };
    responses: {
      /** @description Player updated successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Player"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      404: components["responses"]["NotFound"];
    };
  };
  listRounds: {
    parameters: {
      query?: {
        /** @description Limit the number of rounds returned. Defaults to 20 when omitted. */
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A list of recent rounds. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Round"][];
        };
      };
    };
  };
  createRound: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RoundCreate"];
      };
    };
    responses: {
      /** @description Round created successfully. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Round"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
    };
  };
  getLatestRound: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The most recent round or null when no rounds exist. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Round"] | null;
        };
      };
    };
  };
  getRound: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        roundId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Round details. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Round"];
        };
      };
      404: components["responses"]["NotFound"];
    };
  };
  updateRound: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        roundId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RoundUpdate"];
      };
    };
    responses: {
      /** @description Round updated successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Round"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      409: components["responses"]["Conflict"];
    };
  };
  deleteRound: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        roundId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Round deleted successfully. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
    };
  };
  listFettmattis: {
    parameters: {
      query?: {
        /** @description Limit the number of FettMattis entries returned. Defaults to 20 when omitted. */
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A list of recent FettMattis entries. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FettMattis"][];
        };
      };
    };
  };
  createFettmattis: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FettMattisCreate"];
      };
    };
    responses: {
      /** @description FettMattis created successfully. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FettMattis"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      409: components["responses"]["Conflict"];
    };
  };
  deleteFettmattis: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        fettmattisId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description FettMattis revoked successfully. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
    };
  };
  getRegularLeaderboard: {
    parameters: {
      query?: {
        /** @description Filter results by season; use "all" to view the all-time leaderboard. */
        year?: number | "all";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The regular season leaderboard. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RegularLeaderboardItem"][];
        };
      };
    };
  };
  getFettmattisLeaderboard: {
    parameters: {
      query?: {
        /** @description Filter results by season; use "all" to view the all-time leaderboard. */
        year?: number | "all";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The Fettmattis leaderboard. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FettmattisLeaderboardItem"][];
        };
      };
    };
  };
  listLeaderboardSeasons: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Available leaderboard seasons. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LeaderboardSeasonsResponse"];
        };
      };
    };
  };
}
