services:
  postgres:
    # https://docs.aws.amazon.com/AmazonRDS/latest/AuroraPostgreSQLReleaseNotes/aurorapostgresql-release-calendar.html
    image: postgres:17
    environment:
      POSTGRES_USER: mattis
      POSTGRES_PASSWORD: mattis
      POSTGRES_DB: mattis
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "mattis"]
      interval: 10s
      timeout: 5s
      retries: 5
